// Flat ESLint config. Deliberately small: the rules here are the ones that
// have actually caught bugs in this codebase, not a style opinion dump —
// formatting is not litigated, correctness is.
//
// The heavyweight `eslint-config-next` preset is NOT used: it drags in a
// vulnerable transitive dependency tree (brace-expansion DoS) for rules we
// mostly get from TypeScript already. The two plugins that HAVE caught real
// bugs here — react-hooks (stale closures, missing deps) and the Next
// hazards plugin — are wired directly.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  {
    ignores: [
      ".next/**",
      ".next-live/**",
      "node_modules/**",
      "out/**",
      "coverage/**",
      "next-env.d.ts",   // generated by Next, "should not be edited"
      "playwright-report/**",
      "test-results/**",
      "scripts/**",       // plain node utilities, checked by running them
      "*.config.mjs",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "@next/next": nextPlugin, "react-hooks": reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // unused code is usually a half-finished refactor; allow the _prefix escape
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // `any` disables the type system exactly where bugs hide
      "@typescript-eslint/no-explicit-any": "error",
      // a floating promise is a silently swallowed failure — the reason
      // several "why didn't it save?" bugs are hard to find
      "no-void": "off",
      // Zustand-persist rehydration (`useXxxReady()`) legitimately sets state
      // in an effect: it is synchronising React with an external store that
      // only exists after mount. Kept visible as a warning so a genuinely
      // accidental cascade still gets noticed in review.
      "react-hooks/set-state-in-effect": "warn",
      // React hook deps are enforced by the compiler in dev; these two are
      // the runtime footguns TypeScript can't see
      eqeqeq: ["error", "smart"],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    // tests may reach for looser typing when constructing fixtures
    files: ["tests/**/*.ts", "e2e/**/*.ts"],
    rules: { "@typescript-eslint/no-explicit-any": "off", "no-console": "off" },
  }
);
